# Generated by Django 5.1.5 on 2025-01-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="chat_id"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username_tg",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="username tg"
            ),
        ),
    ]
