# Generated by Django 5.1.5 on 2025-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_chat_id_user_username_tg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username_tg",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="username_tg"
            ),
        ),
    ]
