# Generated by Django 5.1.5 on 2025-01-29 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="last_action_date",
            field=models.DateField(
                blank=True,
                help_text="Введите дату последнего выполнения привычки",
                null=True,
                verbose_name="Дата последнего выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 1, 29, 10, 28, 52, 557047, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время выполнения",
            ),
        ),
    ]
