# Generated by Django 5.1.5 on 2025-01-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habits",
            old_name="user",
            new_name="creator",
        ),
    ]
