# Generated by Django 5.1.5 on 2025-01-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_habits_last_action_date_alter_habits_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 1, 29, 17, 43, 2, 693651, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time_to_action",
            field=models.PositiveIntegerField(
                default=60, verbose_name="Время на выполнения"
            ),
        ),
    ]
