# Generated by Django 5.1.5 on 2025-01-29 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_habits_time_alter_habits_time_to_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="time",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 1, 29, 18, 13, 19, 94453, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time_to_action",
            field=models.DurationField(
                default=datetime.timedelta(seconds=60),
                verbose_name="Время на выполнение",
            ),
        ),
    ]
