# Generated by Django 5.1.5 on 2025-02-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_habits_time"),
        ("tracker", "0003_rename_user_habits_creator"),
    ]

    operations = []
