# Generated by Django 5.1.5 on 2025-02-05 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_merge_20250204_1741"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habits",
            old_name="creator",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="habits",
            name="time",
            field=models.TimeField(
                default=datetime.time(16, 8, 2, 662822), verbose_name="Время выполнения"
            ),
        ),
    ]
