name: Test

on:
  push:
    branches: [feature4-server]
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Run Django tests with unittest
        run: |
            python manage.py test
        env:
          SECRET_KEY: test_secret_key
        timeout-minutes: 5
        continue-on-error: false

      - name: Install coverage
        run: pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test
          coverage xml
          coverage html

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

  docker-build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t CP5 .
