name: Test

on:
  push:
    branches: [feature4-server]
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry update

    - name: Lint with flake8
      run: flake8 .

    - name: Run tests
      run: python manage.py test

  docker-build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t CP5 .
