name: Test

on:
  push:
    branches: [feature4-server]
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Apply migrations
        run: |
          python manage.py migrate      

      - name: Lint with flake8
        run: flake8 .

      - name: Debug environment variables
        run: |
          echo "SECRET_KEY: $SECRET_KEY"

      - name: Run Django tests with unittest
        run: python manage.py test
        env:
          DJANGO_SECRET_KEY: test_secret_key

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

  docker-build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t CP5 .